Vector
Stepavly/first-term pull request #2
Opened 2020-07-02 17:32 UTC by Stepavly

2020-07-02 20:02 UTC, kt-cpp requested changes

2020-07-02 20:02 UTC, kt-cpp commented on vector/vector.h
> +void vector<T>::clear_data_buffer(T *&data_buffer, size_t filled_size) {
T *& это who и for what

2020-07-02 20:02 UTC, kt-cpp commented on vector/vector.h
> +	data_ = static_cast<T *>(operator new(capacity_ * sizeof(T)));
nullptr и лучше все через список инициализации типа vector() : ... {}

2020-07-02 20:02 UTC, kt-cpp commented on vector/vector.h
> +	std::swap(data_buffer_, data_);
присвоение

2020-07-02 20:02 UTC, kt-cpp commented on vector/vector.h
> +		for (size_t i = 0; i < rhs.size_; i++) {
i это и есть filled_size

2020-07-02 20:02 UTC, kt-cpp commented on vector/vector.h
> +	size_ = 0;
какой-то нелогичный порядок, почему не выполнить все удаления, потом присвоить 0 и нуллптр?

2020-07-02 20:02 UTC, kt-cpp commented on vector/vector.h
> +	T push_value(value);
копирование нужно не во всех случаях

2020-07-02 20:02 UTC, kt-cpp commented on vector/vector.h
> +	new(data_ + size_++) T(push_value);
если new упадет, то size все равно увеличится

2020-07-02 20:02 UTC, kt-cpp commented on vector/vector.h
> +	size_t pos_ = pos - begin();
нужен правильный тип для поинтер арифметики

2020-07-02 20:02 UTC, kt-cpp commented on vector/vector.h
> +	if (capacity_ == size_) {
почему не поменять условие и вместо ретурна написать shrink_to_size? ну красивее же

2020-07-02 20:02 UTC, kt-cpp commented on vector/vector.h
> +	T *data_buffer_ = create_data_buffer(new_size);
такой код уже есть в копиконструкторе. нужен общий метод

2020-07-02 20:02 UTC, kt-cpp commented on vector/vector.h
> +	std::swap(data_, data_buffer_);
ну опять присвоение

2020-07-02 20:02 UTC, kt-cpp commented on vector/vector.h
> +void vector<T>::clear() {
а в erase ты делаешь цикл с pop_back(). нужно что-то универсальное

2020-07-05 10:06 UTC, Stepavly commented on vector/vector.h
> +void vector<T>::clear_data_buffer(T *&data_buffer, size_t filled_size) {
`T*&` нужно было, чтобы превращать `data_buffer` в `nullptr` превращать после удаления. Теперь избавился от этого.

2020-07-05 10:06 UTC, Stepavly commented on vector/vector.h
> +	data_ = static_cast<T *>(operator new(capacity_ * sizeof(T)));
fixed.

2020-07-05 10:07 UTC, Stepavly commented on vector/vector.h
> +	std::swap(data_buffer_, data_);
fixed.

2020-07-05 10:07 UTC, Stepavly commented on vector/vector.h
> +		for (size_t i = 0; i < rhs.size_; i++) {
fixed.

2020-07-05 10:07 UTC, Stepavly commented on vector/vector.h
> +	size_ = 0;
fixed.

2020-07-05 10:07 UTC, Stepavly commented on vector/vector.h
> +	T push_value(value);
fixed.

2020-07-05 10:07 UTC, Stepavly commented on vector/vector.h
> +	new(data_ + size_++) T(push_value);
fixed.

2020-07-05 10:08 UTC, Stepavly commented on vector/vector.h
> +	size_t pos_ = pos - begin();
`size_t` --> `ptrdiff_t`.

2020-07-05 10:08 UTC, Stepavly commented on vector/vector.h
> +	if (capacity_ == size_) {
fixed.

2020-07-05 10:09 UTC, Stepavly commented on vector/vector.h
> +	T *data_buffer_ = create_data_buffer(new_size);
Сделал для этого метод `copy_data`.

2020-07-05 10:09 UTC, Stepavly commented on vector/vector.h
> +	std::swap(data_, data_buffer_);
fixed.

2020-07-05 10:09 UTC, Stepavly commented on vector/vector.h
> +void vector<T>::clear() {
fixed.

2020-07-06 17:23 UTC, kt-cpp requested changes

2020-07-06 17:23 UTC, kt-cpp commented on vector/vector.h
> +template<typename T>
новая строка?

2020-07-06 17:23 UTC, kt-cpp commented on vector/vector.h
> +template<typename T>
новая строка

2020-07-06 17:23 UTC, kt-cpp commented on vector/vector.h
> +	T *data_buffer_ = copy_data(data_, 0u, std::min(size_, new_size), new_size);
size потом забыл переназначить

2020-07-06 17:23 UTC, kt-cpp commented on vector/vector.h
> +	T *data_buffer_ = rhs.capacity_ == 0 ? nullptr : copy_data(rhs.data_, 0, rhs.size_, rhs.size_);
а если rhs.capacity = 10, а  size = 0 ? эту логику лучше внутрь copy_data занести

2020-07-06 17:23 UTC, kt-cpp commented on vector/vector.h
> +	data_ = data_buffer_;
делай порядок присваиваний, как у тебя объявлено в структуре

2020-07-06 17:23 UTC, kt-cpp commented on vector/vector.h
> +		data_buffer[i].~T();
не тот порядок деструкторов

2020-07-06 17:23 UTC, kt-cpp commented on vector/vector.h
> +	iterator erase(iterator pos);
достаточно перегрузок для const_iterator. эти лучше убрать, не плодить ненужные касты

2020-07-06 17:26 UTC, kt-cpp commented
у тебя проблемы с гитом, эта ветка не может быть смержена

2020-07-07 13:09 UTC, Stepavly commented on vector/vector.h
> +template<typename T>
fixed.

2020-07-07 13:09 UTC, Stepavly commented on vector/vector.h
> +template<typename T>
fixed.

2020-07-07 13:10 UTC, Stepavly commented on vector/vector.h
> +	T *data_buffer_ = copy_data(data_, 0u, std::min(size_, new_size), new_size);
fixed.

2020-07-07 13:18 UTC, Stepavly commented on vector/vector.h
> +	T *data_buffer_ = copy_data(data_, 0u, std::min(size_, new_size), new_size);
Тут не надо переназначать `size`, так как я эту функцию ещё использую в `reserve`.

2020-07-07 13:18 UTC, Stepavly commented on vector/vector.h
> +	T *data_buffer_ = rhs.capacity_ == 0 ? nullptr : copy_data(rhs.data_, 0, rhs.size_, rhs.size_);
fixed.

2020-07-07 13:19 UTC, Stepavly commented on vector/vector.h
> +	data_ = data_buffer_;
fixed.

2020-07-07 13:20 UTC, Stepavly commented on vector/vector.h
> +		data_buffer[i].~T();
fixed.

2020-07-07 13:22 UTC, Stepavly commented on vector/vector.h
> +	iterator erase(iterator pos);
fixed.

2020-07-07 17:41 UTC, kt-cpp commented
все равно ребейзнуть нельзя. ок, сделаем просто мердж комит. но убери из дифа asm файлы

2020-09-17 18:30 UTC, kt-cpp requested changes

2020-09-17 18:30 UTC, kt-cpp commented on vector/vector.h
> +	void clear_data_buffer(T *data_buffer, size_t from, size_t count);
[minor] Какие есть причины у этих функций не быть статическими?

2020-09-17 18:30 UTC, kt-cpp commented on vector/vector.h
> +T &vector<T>::front() {
[note] Мог бы и сюда `debug_assert` уж добавить раз создал таковой

2020-09-17 18:30 UTC, kt-cpp commented on vector/vector.h
> +		reserve(capacity_ > 0 ? capacity_ << 1u : 1);
[minor] Можно без этих приколов со сдвигами, компилятор прекрасно справляет сомтимизировать умножение на степень двойки

2020-09-17 18:30 UTC, kt-cpp commented on vector/vector.h
> +void vector<T>::shrink_to_size(size_t new_size) {
Кажется по факту эта функция никогда не меняет size, а только capacity. Логичнее чуть изменить ей название и поставить ассерт, что `new_capacity >= size_`

2020-09-17 18:32 UTC, kt-cpp commented
И поправь пожалуста конфликты про которые говорит гихаб. Можно просто скопировать файл с вектором куда-то. Потом насильно переместить эту ветку на мастер, затем скопировать вектор обратно. А в конце закомитить полученные изменения и форспушнуть

2020-09-17 21:27 UTC, Stepavly commented on vector/vector.h
> +	void clear_data_buffer(T *data_buffer, size_t from, size_t count);
fixed.

2020-09-17 21:27 UTC, Stepavly commented on vector/vector.h
> +T &vector<T>::front() {
fixed.

2020-09-17 21:27 UTC, Stepavly commented on vector/vector.h
> +		reserve(capacity_ > 0 ? capacity_ << 1u : 1);
fixed.

2020-09-17 21:27 UTC, Stepavly commented on vector/vector.h
> +void vector<T>::shrink_to_size(size_t new_size) {
fixed.

2020-09-21 19:11 UTC, kt-cpp requested changes
Теперь всё норм, осталось просто убрать дифф асемблера из PR. Советую сделать это советом с предыдущего ревью или обратиться в ЛС за помощью, если что

2020-09-23 21:37 UTC, kt-cpp approved these changes

2020-09-23 21:37 UTC, merged