Bigint
Stepavly/first-term pull request #3
Opened 2020-07-07 14:19 UTC by Stepavly

2020-07-07 20:30 UTC, kt-cpp commented
А зачем удалять ассемблер в этих коммитах?..
PR должен менять только `big_integer.cpp` и `big_integer.h`, почини это, пожалуйста

2020-07-07 20:58 UTC, Stepavly commented
Случайно добавил файлы ассемблера. Думал, что их наличие создаст merge конфликт, поэтому удалял.

2020-07-07 21:48 UTC, kt-cpp requested changes
Комментарии, помеченные [note], к исправлению не обязательны

2020-07-07 21:48 UTC, kt-cpp commented on bigint/big_integer.h
> +			}
[semantic, minor] Эти строчки не нужны. У `int64_t` определено переполнение, `static_cast` снизу возьмёт нужные биты

2020-07-07 21:48 UTC, kt-cpp commented on bigint/big_integer.h
> +		}
[style] Копипаста

2020-07-07 21:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +typedef std::pair<uint32_t, uint32_t> arithmetic_t;
[style, note] `using` вместо `typedef`

2020-07-07 21:48 UTC, kt-cpp commented on bigint/big_integer.cpp
>  }
[performance, minor] Интересно конечно, но почему бы не использовать вместо этого 64-битную арифметику и сдвиги со статик кастами? Компилятору будет проще это всё оптимизировать.

2020-07-07 21:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +	dig = std::vector<uint32_t>(1, a == INT32_MIN ? static_cast<uint32_t>(INT32_MAX) + 1 : static_cast<uint32_t>(abs(a)));
[style, minor] Раскрой этот тернарник, пожалуйста

2020-07-07 21:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +	dig.push_back(a);
[style, minor] Эти строчки можно совместить в одну (и вообще засунуть это в member initializer list)

2020-07-07 21:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +	for (size_t i = isdigit(str[0]) ? 0 : 1; i < str.size(); ) {
[safety] То есть `"a0"` это валидное число? 
Также, добавь поддержку префиксного `+`

2020-07-07 21:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +		size_t j = i;
[style, note] `j` можно сделать локальнее

2020-07-07 21:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +	normalize();
[note] Лайк за мувы

2020-07-07 21:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +		for (size_t i = a.size(); i > 0; i--) {
[style] Цикл может быть чуть проще, у `size_t` определено переполнение

2020-07-07 21:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +		return *this = -(temp -= *this);
[performance] `operator()` копирует. Эта копия лишняя, когда надо только изменить знак.

2020-07-07 21:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +	} else if (abs(*this) < abs(rhs)) {
[performance] Здесь не нужна копия от `abs`

2020-07-07 21:48 UTC, kt-cpp commented on bigint/big_integer.cpp
> +	return *this *= pow(2, rhs);
[performance] Сдвиги могут быть реализованы оптимальнее, чем через возведение в степень

2020-07-07 22:34 UTC, Stepavly commented on bigint/big_integer.h
> +			}
fixed.

2020-07-07 22:40 UTC, Stepavly commented on bigint/big_integer.h
> +		}
fixed.

2020-07-07 22:41 UTC, Stepavly commented on bigint/big_integer.cpp
> +typedef std::pair<uint32_t, uint32_t> arithmetic_t;
fixed.

2020-07-07 22:58 UTC, Stepavly commented on bigint/big_integer.cpp
>  }
fixed.

2020-07-07 22:58 UTC, Stepavly commented on bigint/big_integer.cpp
> +	dig = std::vector<uint32_t>(1, a == INT32_MIN ? static_cast<uint32_t>(INT32_MAX) + 1 : static_cast<uint32_t>(abs(a)));
fixed.

2020-07-07 22:59 UTC, Stepavly commented on bigint/big_integer.cpp
> +	for (size_t i = isdigit(str[0]) ? 0 : 1; i < str.size(); ) {
fixed.

2020-07-07 23:00 UTC, Stepavly commented on bigint/big_integer.cpp
> +	dig.push_back(a);
fixed.

2020-07-07 23:01 UTC, Stepavly commented on bigint/big_integer.cpp
> +		size_t j = i;
fixed.

2020-07-07 23:05 UTC, Stepavly commented on bigint/big_integer.cpp
> +		for (size_t i = a.size(); i > 0; i--) {
fixed.

2020-07-07 23:13 UTC, Stepavly commented on bigint/big_integer.cpp
> +		return *this = -(temp -= *this);
fixed.

2020-07-07 23:25 UTC, Stepavly commented on bigint/big_integer.cpp
> +	} else if (abs(*this) < abs(rhs)) {
fixed.

2020-07-08 00:15 UTC, Stepavly commented on bigint/big_integer.cpp
> +	return *this *= pow(2, rhs);
fixed.

2020-07-08 00:28 UTC, kt-cpp commented on bigint/big_integer.h
> +			}
точно?)

2020-07-08 00:35 UTC, kt-cpp commented on bigint/big_integer.cpp
> +		for (size_t i = a.size(); i > 0; i--) {
Можно веселее: `i < a.size()` в предикате остановки цикла, ну да ладно

2020-07-08 00:35 UTC, Stepavly commented on bigint/big_integer.h
> +			}
Справедливо, должно быть
`diff = static_cast<uint32_t>(diff);`

2020-07-08 00:36 UTC, Stepavly commented on bigint/big_integer.h
> +			}
Без if'а.

2020-07-08 00:43 UTC, kt-cpp commented on bigint/big_integer.h
> +			}
Поправь, пожалуйста

2020-07-08 00:46 UTC, Stepavly commented on bigint/big_integer.h
> +			}
Уже

2020-07-08 00:47 UTC, kt-cpp requested changes

2020-07-08 00:47 UTC, kt-cpp commented on bigint/big_integer.h
> +	big_integer bit_shift(ptrdiff_t shift) {
[style] Не стоит раздувать размер исходников после препроцессинга, определи эти функции в `.cpp`

2020-07-08 00:47 UTC, kt-cpp commented on bigint/big_integer.cpp
> +			if (!isdigit(str[i])) {
[semantic] Вряд ли ты хочешь 9 раз проверять `str[i]`

2020-07-08 00:47 UTC, kt-cpp commented on bigint/big_integer.cpp
> +	} else if (rhs.size() > size() || !(*this).is_smaller(rhs, size())) {
[style] Для таких случаев придумали оператор `->`

2020-07-08 14:02 UTC, Stepavly commented on bigint/big_integer.cpp
> +			if (!isdigit(str[i])) {
Но я ведь в цикле двигаю `i`.

2020-07-08 14:04 UTC, Stepavly commented on bigint/big_integer.cpp
> +	} else if (rhs.size() > size() || !(*this).is_smaller(rhs, size())) {
fixed.

2020-07-08 14:13 UTC, Stepavly commented on bigint/big_integer.h
> +	big_integer bit_shift(ptrdiff_t shift) {
Перенёс в `.cpp`.

2020-07-08 14:18 UTC, kt-cpp commented on bigint/big_integer.cpp
> +			if (!isdigit(str[i])) {
Ой, точно, не заметил

2020-07-08 14:20 UTC, kt-cpp approved these changes

2020-07-08 14:20 UTC, merged